packages:
  - packages/*
  - packages/testing/*
  - integration/*
allowBuilds:
  '@nestjs/core': true
  esbuild: true
  nx: true
  protobufjs: true
  unrs-resolver: true
overrides:
  js-yaml@^4: ^4.3.2
