export const GOOGLE_CLOUD_PUBSUB_CLIENT_TOKEN = Symbol('GOOGLE_CLOUD_PUBSUB_CLIENT_TOKEN');
export const GOOGLE_CLOUD_PUBSUB_SUBSCRIBE = Symbol('GOOGLE_CLOUD_PUBSUB_SUBSCRIBE');
export const GOOGLE_CLOUD_PUBSUB_BATCH_SUBSCRIBE = Symbol('GOOGLE_CLOUD_PUBSUB_BATCH_SUBSCRIBE');
