// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "level1.proto" (package "example.level1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * @generated from protobuf message example.level1.Level1ProtocolBuffer
 */
export interface Level1ProtocolBuffer {
  /**
   * @generated from protobuf field: string field1 = 1
   */
  field1: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Level1ProtocolBuffer$Type extends MessageType<Level1ProtocolBuffer> {
  constructor() {
    super('example.level1.Level1ProtocolBuffer', [
      { no: 1, name: 'field1', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
    ]);
  }
  create(value?: PartialMessage<Level1ProtocolBuffer>): Level1ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.field1 = '';
    if (value !== undefined)
      reflectionMergePartial<Level1ProtocolBuffer>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level1ProtocolBuffer,
  ): Level1ProtocolBuffer {
    const message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      const [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* string field1 */ 1:
          message.field1 = reader.string();
          break;
        default:
          const u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          const d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level1ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* string field1 = 1; */
    if (message.field1 !== '')
      writer.tag(1, WireType.LengthDelimited).string(message.field1);
    const u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level1.Level1ProtocolBuffer
 */
export const Level1ProtocolBuffer = new Level1ProtocolBuffer$Type();
