// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "level5.proto" (package "example.level5", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * @generated from protobuf message example.level5.Level5ProtocolBuffer
 */
export interface Level5ProtocolBuffer {
  /**
   * @generated from protobuf field: string field1 = 1
   */
  field1: string;
  /**
   * @generated from protobuf field: int32 field2 = 2
   */
  field2: number;
  /**
   * @generated from protobuf field: bool field3 = 3
   */
  field3: boolean;
  /**
   * @generated from protobuf field: double field4 = 4
   */
  field4: number;
  /**
   * @generated from protobuf field: bytes field5 = 5
   */
  field5: Uint8Array;
  /**
   * @generated from protobuf field: repeated string field6 = 6
   */
  field6: string[];
  /**
   * @generated from protobuf field: float field7 = 7
   */
  field7: number;
  /**
   * @generated from protobuf field: int64 field8 = 8
   */
  field8: bigint;
  /**
   * @generated from protobuf field: example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer nested1 = 9
   */
  nested1?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer;
}
/**
 * @generated from protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer
 */
export interface Level5ProtocolBuffer_Nested1L5ProtocolBuffer {
  /**
   * @generated from protobuf field: string nestedField1 = 1
   */
  nestedField1: string;
  /**
   * @generated from protobuf field: example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer nested2 = 2
   */
  nested2?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer;
}
/**
 * @generated from protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer
 */
export interface Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer {
  /**
   * @generated from protobuf field: int32 nestedField2 = 1
   */
  nestedField2: number;
  /**
   * @generated from protobuf field: example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer nested3 = 2
   */
  nested3?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer;
}
/**
 * @generated from protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer
 */
export interface Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer {
  /**
   * @generated from protobuf field: bool nestedField3 = 1
   */
  nestedField3: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Level5ProtocolBuffer$Type extends MessageType<Level5ProtocolBuffer> {
  constructor() {
    super('example.level5.Level5ProtocolBuffer', [
      { no: 1, name: 'field1', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: 'field2', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 3, name: 'field3', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ },
      { no: 4, name: 'field4', kind: 'scalar', T: 1 /*ScalarType.DOUBLE*/ },
      { no: 5, name: 'field5', kind: 'scalar', T: 12 /*ScalarType.BYTES*/ },
      {
        no: 6,
        name: 'field6',
        kind: 'scalar',
        repeat: 2 /*RepeatType.UNPACKED*/,
        T: 9 /*ScalarType.STRING*/,
      },
      { no: 7, name: 'field7', kind: 'scalar', T: 2 /*ScalarType.FLOAT*/ },
      {
        no: 8,
        name: 'field8',
        kind: 'scalar',
        T: 3 /*ScalarType.INT64*/,
        L: 0 /*LongType.BIGINT*/,
      },
      {
        no: 9,
        name: 'nested1',
        kind: 'message',
        T: () => Level5ProtocolBuffer_Nested1L5ProtocolBuffer,
      },
    ]);
  }
  create(value?: PartialMessage<Level5ProtocolBuffer>): Level5ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.field1 = '';
    message.field2 = 0;
    message.field3 = false;
    message.field4 = 0;
    message.field5 = new Uint8Array(0);
    message.field6 = [];
    message.field7 = 0;
    message.field8 = 0n;
    if (value !== undefined)
      reflectionMergePartial<Level5ProtocolBuffer>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level5ProtocolBuffer,
  ): Level5ProtocolBuffer {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* string field1 */ 1:
          message.field1 = reader.string();
          break;
        case /* int32 field2 */ 2:
          message.field2 = reader.int32();
          break;
        case /* bool field3 */ 3:
          message.field3 = reader.bool();
          break;
        case /* double field4 */ 4:
          message.field4 = reader.double();
          break;
        case /* bytes field5 */ 5:
          message.field5 = reader.bytes();
          break;
        case /* repeated string field6 */ 6:
          message.field6.push(reader.string());
          break;
        case /* float field7 */ 7:
          message.field7 = reader.float();
          break;
        case /* int64 field8 */ 8:
          message.field8 = reader.int64().toBigInt();
          break;
        case /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer nested1 */ 9:
          message.nested1 =
            Level5ProtocolBuffer_Nested1L5ProtocolBuffer.internalBinaryRead(
              reader,
              reader.uint32(),
              options,
              message.nested1,
            );
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level5ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* string field1 = 1; */
    if (message.field1 !== '')
      writer.tag(1, WireType.LengthDelimited).string(message.field1);
    /* int32 field2 = 2; */
    if (message.field2 !== 0)
      writer.tag(2, WireType.Varint).int32(message.field2);
    /* bool field3 = 3; */
    if (message.field3 !== false)
      writer.tag(3, WireType.Varint).bool(message.field3);
    /* double field4 = 4; */
    if (message.field4 !== 0)
      writer.tag(4, WireType.Bit64).double(message.field4);
    /* bytes field5 = 5; */
    if (message.field5.length)
      writer.tag(5, WireType.LengthDelimited).bytes(message.field5);
    /* repeated string field6 = 6; */
    for (let i = 0; i < message.field6.length; i++)
      writer.tag(6, WireType.LengthDelimited).string(message.field6[i]);
    /* float field7 = 7; */
    if (message.field7 !== 0)
      writer.tag(7, WireType.Bit32).float(message.field7);
    /* int64 field8 = 8; */
    if (message.field8 !== 0n)
      writer.tag(8, WireType.Varint).int64(message.field8);
    /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer nested1 = 9; */
    if (message.nested1)
      Level5ProtocolBuffer_Nested1L5ProtocolBuffer.internalBinaryWrite(
        message.nested1,
        writer.tag(9, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level5.Level5ProtocolBuffer
 */
export const Level5ProtocolBuffer = new Level5ProtocolBuffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Level5ProtocolBuffer_Nested1L5ProtocolBuffer$Type extends MessageType<Level5ProtocolBuffer_Nested1L5ProtocolBuffer> {
  constructor() {
    super('example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer', [
      {
        no: 1,
        name: 'nestedField1',
        kind: 'scalar',
        T: 9 /*ScalarType.STRING*/,
      },
      {
        no: 2,
        name: 'nested2',
        kind: 'message',
        T: () =>
          Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer,
      },
    ]);
  }
  create(
    value?: PartialMessage<Level5ProtocolBuffer_Nested1L5ProtocolBuffer>,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.nestedField1 = '';
    if (value !== undefined)
      reflectionMergePartial<Level5ProtocolBuffer_Nested1L5ProtocolBuffer>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* string nestedField1 */ 1:
          message.nestedField1 = reader.string();
          break;
        case /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer nested2 */ 2:
          message.nested2 =
            Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer.internalBinaryRead(
              reader,
              reader.uint32(),
              options,
              message.nested2,
            );
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level5ProtocolBuffer_Nested1L5ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* string nestedField1 = 1; */
    if (message.nestedField1 !== '')
      writer.tag(1, WireType.LengthDelimited).string(message.nestedField1);
    /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer nested2 = 2; */
    if (message.nested2)
      Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer.internalBinaryWrite(
        message.nested2,
        writer.tag(2, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer
 */
export const Level5ProtocolBuffer_Nested1L5ProtocolBuffer =
  new Level5ProtocolBuffer_Nested1L5ProtocolBuffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer$Type extends MessageType<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer> {
  constructor() {
    super(
      'example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer',
      [
        {
          no: 1,
          name: 'nestedField2',
          kind: 'scalar',
          T: 5 /*ScalarType.INT32*/,
        },
        {
          no: 2,
          name: 'nested3',
          kind: 'message',
          T: () =>
            Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer,
        },
      ],
    );
  }
  create(
    value?: PartialMessage<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer>,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.nestedField2 = 0;
    if (value !== undefined)
      reflectionMergePartial<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* int32 nestedField2 */ 1:
          message.nestedField2 = reader.int32();
          break;
        case /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer nested3 */ 2:
          message.nested3 =
            Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer.internalBinaryRead(
              reader,
              reader.uint32(),
              options,
              message.nested3,
            );
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* int32 nestedField2 = 1; */
    if (message.nestedField2 !== 0)
      writer.tag(1, WireType.Varint).int32(message.nestedField2);
    /* example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer nested3 = 2; */
    if (message.nested3)
      Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer.internalBinaryWrite(
        message.nested3,
        writer.tag(2, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer
 */
export const Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer =
  new Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer$Type extends MessageType<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer> {
  constructor() {
    super(
      'example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer',
      [
        {
          no: 1,
          name: 'nestedField3',
          kind: 'scalar',
          T: 8 /*ScalarType.BOOL*/,
        },
      ],
    );
  }
  create(
    value?: PartialMessage<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer>,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.nestedField3 = false;
    if (value !== undefined)
      reflectionMergePartial<Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer>(
        this,
        message,
        value,
      );
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer,
  ): Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* bool nestedField3 */ 1:
          message.nestedField3 = reader.bool();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* bool nestedField3 = 1; */
    if (message.nestedField3 !== false)
      writer.tag(1, WireType.Varint).bool(message.nestedField3);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level5.Level5ProtocolBuffer.Nested1L5ProtocolBuffer.Nested2L5ProtocolBuffer.Nested3L5ProtocolBuffer
 */
export const Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer =
  new Level5ProtocolBuffer_Nested1L5ProtocolBuffer_Nested2L5ProtocolBuffer_Nested3L5ProtocolBuffer$Type();
