export const STRIPE_CLIENT_TOKEN = Symbol('STRIPE_CLIENT_TOKEN');

export const STRIPE_WEBHOOK_HANDLER = Symbol('STRIPE_WEBHOOK_HANDLER');

export const STRIPE_WEBHOOK_SERVICE = Symbol('STRIPE_WEBHOOK_SERVICE');

export const STRIPE_WEBHOOK_CONTEXT_TYPE = 'stripe_webhook';
