// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "level2.proto" (package "example.level2", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from '@protobuf-ts/runtime';
import type { IBinaryWriter } from '@protobuf-ts/runtime';
import { WireType } from '@protobuf-ts/runtime';
import type { BinaryReadOptions } from '@protobuf-ts/runtime';
import type { IBinaryReader } from '@protobuf-ts/runtime';
import { UnknownFieldHandler } from '@protobuf-ts/runtime';
import type { PartialMessage } from '@protobuf-ts/runtime';
import { reflectionMergePartial } from '@protobuf-ts/runtime';
import { MessageType } from '@protobuf-ts/runtime';
/**
 * @generated from protobuf message example.level2.Level2ProtocolBuffer
 */
export interface Level2ProtocolBuffer {
  /**
   * @generated from protobuf field: string field1 = 1
   */
  field1: string;
  /**
   * @generated from protobuf field: int32 field2 = 2
   */
  field2: number;
  /**
   * @generated from protobuf field: bool field3 = 3
   */
  field3: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class Level2ProtocolBuffer$Type extends MessageType<Level2ProtocolBuffer> {
  constructor() {
    super('example.level2.Level2ProtocolBuffer', [
      { no: 1, name: 'field1', kind: 'scalar', T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: 'field2', kind: 'scalar', T: 5 /*ScalarType.INT32*/ },
      { no: 3, name: 'field3', kind: 'scalar', T: 8 /*ScalarType.BOOL*/ },
    ]);
  }
  create(value?: PartialMessage<Level2ProtocolBuffer>): Level2ProtocolBuffer {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.field1 = '';
    message.field2 = 0;
    message.field3 = false;
    if (value !== undefined)
      reflectionMergePartial<Level2ProtocolBuffer>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: Level2ProtocolBuffer,
  ): Level2ProtocolBuffer {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* string field1 */ 1:
          message.field1 = reader.string();
          break;
        case /* int32 field2 */ 2:
          message.field2 = reader.int32();
          break;
        case /* bool field3 */ 3:
          message.field3 = reader.bool();
          break;
        default:
          let u = options.readUnknownField;
          if (u === 'throw')
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: Level2ProtocolBuffer,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* string field1 = 1; */
    if (message.field1 !== '')
      writer.tag(1, WireType.LengthDelimited).string(message.field1);
    /* int32 field2 = 2; */
    if (message.field2 !== 0)
      writer.tag(2, WireType.Varint).int32(message.field2);
    /* bool field3 = 3; */
    if (message.field3 !== false)
      writer.tag(3, WireType.Varint).bool(message.field3);
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message example.level2.Level2ProtocolBuffer
 */
export const Level2ProtocolBuffer = new Level2ProtocolBuffer$Type();
