export const HASURA_EVENT_HANDLER = Symbol('HASURA_EVENT_HANDLER');
export const HASURA_ACTION_HANDLER = Symbol('HASURA_ACTION_HANDLER');
export const HASURA_ACTION_INPUT_SDL = 'HASURA_ACTION_INPUT_SDL';
export const HASURA_MODULE_CONFIG = Symbol('HASURA_MODULE_CONFIG');
