export const HASURA_EVENT_HANDLER = Symbol('HASURA_EVENT_HANDLER');
export const HASURA_MODULE_CONFIG = Symbol('HASURA_MODULE_CONFIG');
export const HASURA_SCHEDULED_EVENT_HANDLER = Symbol(
  'HASURA_SCHEDULED_EVENT_HANDLER'
);
